### ISSUE TITLE
Add explanation of smart contract invokation

### ISSUE THREAD

**Issue by chrmatt** [Concordium/concordium.github.io#661]
**Description**
For smart contract development, it would be good to have an explanation with examples of how to use functions such as `invoke_contract_raw`.

Note that there is a page "Initialize a smart contract instance" in the "On-chain guides", but this discusses another topic. It would be good to have a clear terminology to avoid confusion.

**Comment by dg-concordium** [comment]
Comments from Slack exchange: 
DG: I am a bit confused about your issue here. You say that some of the more obscure functions should be documented, like invoke_contract_raw. But in the next paragraph you mention a guide about initalization. Did you mean the guide about invoke instead? https://developer.concordium.software/en/mainnet/smart-contracts/guides/invoke-instance.html
[3:32](https://concordium.slack.com/archives/D03S1RLU537/p1671460376281679)
I'm not clear what you mean. Initizlize and invoke are two distinct things as I understand it.
CM: Yes, you are right, I meant the page about invoke

It's rather confusing since one invoke means to simulate it for testing the outcome, and the other is actually calling it on chain. It would be good to not both call them invoke.
